services:
  database:
    image: "mysql:8.0"
    container_name: mysql-warehouse
    hostname: database
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root123t4ng
      MYSQL_DATABASE: warehouse_inventory
      MYSQL_USER: sqluser
      MYSQL_PASSWORD: 123sqly6
    volumes:
      - ./db-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - warehouse-net

networks:
  warehouse-net:
    name: warehouse-net
    driver: bridge
    external: false
